import { Injectable } from "@nestjs/common";

import type { AgentDecision, AgentMode } from "@project/shared";

import { FakeRuleAgentAdapter } from "./adapters/fake-rule-agent.adapter.js";

@Injectable()
export class AgentService {
  constructor(private readonly fakeAdapter: FakeRuleAgentAdapter) {}

  async decide(message: string, mode: AgentMode): Promise<AgentDecision> {
    // 预留: mode=llm/auto 时可切换到真实 LLM adapter。
    const modelOutput = await this.fakeAdapter.decide({
      message,
      mode,
      availableTools: ["getOrder", "getDoctor"]
    });

    return {
      intent: modelOutput.intent,
      confidence: modelOutput.confidence,
      shouldCallTools: modelOutput.toolCalls.length > 0,
      toolCalls: modelOutput.toolCalls,
      fallbackText: modelOutput.replyDraft,
      mode,
      reason:
        modelOutput.toolCalls.length > 0
          ? "Keyword matched, tool call generated by fake rule adapter"
          : "No keyword matched, returning fallback text"
    };
  }
}
